server:
  port: 3344

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka1:7001/eureka/
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shanxianyue/springcloud-config
          username: shanxianyue
          password: 1991a0727a
          search-paths:
            - springcloud-config
      label: master
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
