server:
  port: 80

spring:
  application:
    name: cloud-feign-order-service



eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka,http://eureka2:7002/eureka
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true
    #eureka客户端向服务端发送心跳的时间间隔，单位：秒(默认是30秒)
    lease-renewal-interval-in-seconds: 1
    #eureka服务端在收到最后一次心跳后等待的时间上限，单位为秒（默认为90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 2
#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.atguigu.feign.PaymentFeignClient: debug